[package]
name = "moveFiles-service"
version = "1.0.1"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
colored = "2.0.0"
fs_extra = "1.3.0"
walkdir = "2"

[build-dependencies]
winresource = "0.1.14"